name: Cypress tests
on:
  push:
  workflow_dispatch:
jobs:
  all-but-burn:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:all:but:burn:cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  burn:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:burn:cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
